blogTitle = "Scott Nonnenberg"
domain = "https://blog.scottnonnenberg.com"
linkPrefix = "/"

noProductionJavascript = true

favicon = "/favicon.ico"
tagLine = "A blog about <a href='/tags/software/?tagline'>software development</a> and <a href='/star-wars-cards/?tagline'>geekery</a> <a href='/woot-shirts/?tagline'>of</a> <a href='/cycling-computers-and-posture/?tagline'>all</a> <a href='/a-35lb-weight-swing-in-two-years/?tagline'>kinds</a>."
domainCDN = "https://static.sinap.ps"

authorShortName = "Scott"
authorName = "Scott Nonnenberg"
authorEmail = "scott@nonnenberg.com"
authorTwitter = "@scottnonnenberg"
authorURL = "https://scottnonnenberg.com"
authorImage = "https://static.sinap.ps/img/profile/me_2012_square_300px_full.png"
authorIcon = "https://static.sinap.ps/img/profile/me_2012_square_300px.jpg"
authorBlurb = "Hi, I'm <a href='https://scottnonnenberg.com'><strong>Scott</strong></a>. I've written both server and client code in <a href=\"/eslint-part-3-analysis/#your-fingerprint\">many languages</a> for <a href=\"https://scottnonnenberg.com/work\">many employers and clients</a>. I've also got a bit of an <a href=\"/contract-an-unusual-skillset/\">unusual</a> <a href=\"/from-tech-person-to-people-person/\">perspective</a>, since I've spent time in <a href=\"https://scottnonnenberg.com/work/#microsoft-2010-q-3-to-2011-q-3\">roles</a> <a href=\"https://scottnonnenberg.com/work/#nordstrom-2012-q-2-to-q-4\">outside</a> <a href=\"https://scottnonnenberg.com/work/#social-security-administration-2015-q-3\">the</a> pure 'software developer.'"
