blogTitle = "Scott Nonnenberg"
domain = "https://blog.scottnonnenberg.com"
linkPrefix = "/"

noProductionJavascript = true

favicon = "/favicon.ico"
tagLine = "A blog about <a href='/tags/software/?tagline'>software development</a> and <a href='/star-wars-cards/?tagline'>geekery</a> <a href='/woot-shirts/?tagline'>of</a> <a href='/cycling-computers-and-posture/?tagline'>all</a> <a href='/a-35lb-weight-swing-in-two-years/?tagline'>kinds</a>."
domainCDN = "https://static.sinap.ps"

authorShortName = "Scott"
authorName = "Scott Nonnenberg"
authorEmail = "scott@nonnenberg.com"
authorTwitter = "@scottnonnenberg"
authorURL = "https://scottnonnenberg.com"
authorImage = "https://static.sinap.ps/img/profile/me_2012_square_300px_full.png"
authorIcon = "https://static.sinap.ps/img/profile/me_2012_square_300px.jpg"
authorBlurb = "Hi, I'm <a href='https://scottnonnenberg.com'><strong>Scott</strong></a>. I've been in software <a href='https://scottnonnenberg.com/work/'>a long time</a>, and during most of that time I have worked to <a href='/from-tech-person-to-people-person/'>bridge the people/tech divide</a>. <a class='call-to-action' href='mailto:scott@nonnenberg.com'>Contact me</a> if your company needs training, coding, or just an experienced outside perspective!"

