blogTitle = "Scott Nonnenberg"
domain = "https://blog.scottnonnenberg.com"
linkPrefix = "/"

noProductionJavascript = true

favicon = "/favicon.ico"
tagLine = "A blog about software development and geekery of all kinds."
domainCDN = "https://static.sinap.ps"
domainPiwik = "https://piwik.sinap.ps"

authorShortName = "Scott"
authorName = "Scott Nonnenberg"
authorEmail = "scott@nonnenberg.com"
authorTwitter = "@scottnonnenberg"
authorURL = "https://scottnonnenberg.com"
authorImage = "https://static.sinap.ps/img/profile/me_2012_square_80px.jpg"
authorBlurb = "Hi, I'm <a href='https://scottnonnenberg.com'><strong>Scott</strong></a>. I'm a <a href='http://calpoly.edu'>Computer Science major</a> turned <a href='http://visualstudio.com'>Visual Studio</a> program manager, now consultant and entrepreneur. <a href='mailto:scott@nonnenberg.com'>Contact me</a> if you need some training, coding, or just an experienced outside perspective!"
